Update model_uploader.yml
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -56,11 +56,11 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref != 'refs/heads/main'
-      run: |
-         echo "This workflow should only be triggered on 'main' branch"
-         exit 1
+    # - name: Fail if branch is not main
+    #   if: github.ref != 'refs/heads/main'
+    #   run: |
+    #      echo "This workflow should only be triggered on 'main' branch"
+    #      exit 1
     - name: Initiate folders
       id: init_folders
       run: |
@@ -111,7 +111,6 @@ jobs:
   # Step 3: Check if the model already exists in the model hub
   checking-out-model-hub:
     needs: init-workflow-var
-    if: github.event.inputs.allow_overwrite == 'NO'
     runs-on: 'ubuntu-latest'
     permissions:
       id-token: write
@@ -131,7 +130,7 @@ jobs:
           role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
           role-session-name: checking-out-model-hub
       - name: Check if TORCH_SCRIPT Model Exists
-        if: github.event.inputs.tracing_format == 'TORCH_SCRIPT' || github.event.inputs.tracing_format == 'BOTH'
+        if: github.event.inputs.allow_overwrite == 'NO' && (github.event.inputs.tracing_format == 'TORCH_SCRIPT' || github.event.inputs.tracing_format == 'BOTH')
         run: |
           TORCH_FILE_PATH=$(python utils/model_uploader/save_model_file_path_to_env.py \
               ${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} ${{ github.event.inputs.model_id }} \
@@ -143,7 +142,7 @@ jobs:
             exit 1
           fi
       - name: Check if ONNX Model Exists
-        if: github.event.inputs.tracing_format == 'ONNX' || github.event.inputs.tracing_format == 'BOTH'
+        if: github.event.inputs.allow_overwrite == 'NO' && (github.event.inputs.tracing_format == 'ONNX' || github.event.inputs.tracing_format == 'BOTH')
         run: |
           ONNX_FILE_PATH=$(python utils/model_uploader/save_model_file_path_to_env.py \
             ${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} ${{ github.event.inputs.model_id }} \
@@ -158,7 +157,6 @@ jobs:
   # Step 4: Trace the model, Verify the embeddings & Upload the model files as artifacts
   model-auto-tracing:
     needs: [init-workflow-var, checking-out-model-hub]
-    if:  always() && needs.init-workflow-var.result == 'success' && (needs.checking-out-model-hub.result == 'success' || needs.checking-out-model-hub.result == 'skipped')
     name: model-auto-tracing
     runs-on: ubuntu-latest
     permissions:
@@ -219,22 +217,22 @@ jobs:
           path: ./upload/
           retention-days: 5
           if-no-files-found: error
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
-          role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
-          role-session-name: model-auto-tracing
-      - name: Dryrun model uploading
-        id: dryrun_model_uploading
-        run: |
-          dryrun_output=$(aws s3 sync ./upload/ s3://${{ secrets.MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} --dryrun \
-            | sed 's|s3://${{ secrets.MODEL_BUCKET }}/|s3://(MODEL_BUCKET)/|' 
-          )
-          echo "dryrun_output<<EOF" >> $GITHUB_OUTPUT
-          echo "${dryrun_output@E}" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          echo "${dryrun_output@E}"
+      # - name: Configure AWS Credentials
+      #   uses: aws-actions/configure-aws-credentials@v2
+      #   with:
+      #     aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
+      #     role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
+      #     role-session-name: model-auto-tracing
+      # - name: Dryrun model uploading
+      #   id: dryrun_model_uploading
+      #   run: |
+      #     dryrun_output=$(aws s3 sync ./upload/ s3://${{ secrets.MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} --dryrun \
+      #       | sed 's|s3://${{ secrets.MODEL_BUCKET }}/|s3://(MODEL_BUCKET)/|' 
+      #     )
+      #     echo "dryrun_output<<EOF" >> $GITHUB_OUTPUT
+      #     echo "${dryrun_output@E}" >> $GITHUB_OUTPUT
+      #     echo "EOF" >> $GITHUB_OUTPUT
+      #     echo "${dryrun_output@E}"
     outputs:
       license_line: ${{ steps.license_verification.outputs.license_line }}
       license_info: ${{ steps.license_verification.outputs.license_info }}
