Update model_uploader.yml
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -173,6 +173,16 @@ jobs:
           echo "MODEL_DESCRIPTION=${{ github.event.inputs.model_description }}" >> $GITHUB_ENV     
       - name: Autotracing ${{ matrix.cluster }} secured=${{ matrix.secured }} version=${{matrix.entry.opensearch_version}}
         run: "./.ci/run-tests ${{ matrix.cluster }} ${{ matrix.secured }} ${{ matrix.entry.opensearch_version }} trace"
+      - name: Limit Model Size to 2GB
+        run: |
+          upload_size=$(ls -lR ./upload/ | awk '{ SUM += $5} END {print SUM}')
+          limit="2147483648" 
+          echo "Model Artifact Size: $upload_size"
+          if [ "$upload_size" -ge "$limit" ]
+          then
+            echo "The workflow cannot upload the model artifact that is larger than 2GB."
+            exit 1
+          fi
       - name: License Verification
         id: license_verification
         run: |
