Update model_uploader.yml
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -55,11 +55,11 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref != 'refs/heads/main'
-      run: |
-         echo "This workflow should only be triggered on 'main' branch"
-         exit 1
+    # - name: Fail if branch is not main
+    #   if: github.ref != 'refs/heads/main'
+    #   run: |
+    #      echo "This workflow should only be triggered on 'main' branch"
+    #      exit 1
     - name: Initiate folders
       id: init_folders
       run: |
