Merge experiment-description
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -38,18 +38,21 @@ on:
         - "MEAN"
         - "MAX"
         - "MEAN_SQRT_LEN"
+      model_description:
+        description: "(Optional) Description (Specify here if you want to overwrite the default model description)"
+        required: false
+        type: string
 
 jobs:
   # Step 2: Initiate workflow variable
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref != 'refs/heads/workflow-for-review' # TO-BE-CHANGED
-      #if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
-      run: |
-        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
-        exit 1
+#     - name: Fail if branch is not main
+#       if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+#       run: |
+#          echo "This workflow should only be triggered on a default branch"
+#          exit 1
     - name: Initiate model_folder
       id: init_model_folder
       run: |
@@ -60,6 +63,7 @@ jobs:
       run: |
         embedding_dimension=${{ github.event.inputs.embedding_dimension }}
         pooling_mode=${{ github.event.inputs.pooling_mode }}
+        model_description="${{ github.event.inputs.model_description }}"
         
         workflow_info="
         ========= Workflow Details ==========
@@ -73,6 +77,7 @@ jobs:
         - Tracing Format: ${{ github.event.inputs.tracing_format }}
         - Embedding Dimension: ${embedding_dimension:-Default}
         - Pooling Mode: ${pooling_mode:-Default}
+        - Model Description: \"${model_description:-Default}\"
         
         ========= Test Information ==========
         - Embedding Verification: Passed"
@@ -163,6 +168,7 @@ jobs:
           echo "TRACING_FORMAT=${{ github.event.inputs.tracing_format }}" >> $GITHUB_ENV
           echo "EMBEDDING_DIMENSION=${{ github.event.inputs.embedding_dimension }}" >> $GITHUB_ENV
           echo "POOLING_MODE=${{ github.event.inputs.pooling_mode }}" >> $GITHUB_ENV     
+          echo "MODEL_DESCRIPTION=${{ github.event.inputs.model_description }}" >> $GITHUB_ENV     
       - name: Autotracing ${{ matrix.cluster }} secured=${{ matrix.secured }} version=${{matrix.entry.opensearch_version}}
         run: "./.ci/run-tests ${{ matrix.cluster }} ${{ matrix.secured }} ${{ matrix.entry.opensearch_version }} trace"
       - name: License verification
@@ -295,12 +301,14 @@ jobs:
           python -m pip install mdutils
       - name: Update Model Upload History
         run: |
+          model_description="${{ github.event.inputs.model_description }}"
           python utils/model_uploader/update_models_upload_history_md.py \
             ${{ github.event.inputs.model_id }} \
             ${{ github.event.inputs.model_version }} \
             ${{ github.event.inputs.tracing_format }} \
             -ed ${{ github.event.inputs.embedding_dimension }} \
             -pm ${{ github.event.inputs.pooling_mode }} \
+            -md ${model_description:+"$model_description"} \
             -u ${{ github.actor }} -t "${{ needs.model-uploading.outputs.upload_time }}"
       - name: Create PR Body
         id: create_pr_body
