add fields and check
Signed-off-by: zhichao-aws <zhichaog@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -8,6 +8,14 @@ on:
         required: true
         type: string
         default: "huggingface"
+      model_license:
+        description: "Model license (e.g. Apache-2.0)"
+        required: true
+        type: choice
+        default: "Apache-2.0"
+        options:
+          - "Apache-2.0"
+          - "MIT"
       model_id:
         description: "Model ID for auto-tracing and uploading (e.g. sentence-transformers/msmarco-distilbert-base-tas-b)"
         required: true
@@ -49,7 +57,18 @@ on:
         options:
         - "NO"
         - "YES"
-        
+      mit_copyright_statement:
+        description: "(Optional) Copyright statement for MIT licensed models. Should be picked from origin MIT license file. E.g. Copyright (c) {year} {author}"
+        required: false
+        type: string
+      mit_attribution_website:
+        description: "(Optional) The project website for MIT licensed models. The MIT license file is supposed to be found in this website"
+        required: false
+        type: string
+      mit_model_version:
+        description: "(Optional) The model version for MIT licensed models. Different from the model_version field above, this version should be quoted from the origin project website."
+        required: false
+        type: string
 
 jobs:
   # Step 2: Initiate workflow variable
@@ -73,6 +92,9 @@ jobs:
         embedding_dimension=${{ github.event.inputs.embedding_dimension }}
         pooling_mode=${{ github.event.inputs.pooling_mode }}
         model_description="${{ github.event.inputs.model_description }}"
+        mit_copyright_statement="${{ github.event.inputs.mit_copyright_statement }}"
+        mit_attribution_website="${{ github.event.inputs.mit_attribution_website }}"
+        mit_model_version="${{ github.event.inputs.mit_model_version }}"
         
         workflow_info="
         ============= Workflow Details ==============
@@ -83,11 +105,15 @@ jobs:
           
         ========= Workflow Input Information =========
         - Model ID: ${{ github.event.inputs.model_id }}
+        - Model License ${{ github.event.inputs.model_license }}
         - Model Version: ${{ github.event.inputs.model_version }}
         - Tracing Format: ${{ github.event.inputs.tracing_format }}
         - Embedding Dimension: ${embedding_dimension:-N/A}
         - Pooling Mode: ${pooling_mode:-N/A}
         - Model Description: ${model_description:-N/A}
+        - MIT Copyright Statement: ${mit_copyright_statement:-N/A}
+        - MIT Attribution Website: ${mit_attribution_website:-N/A}
+        - MIT Model Version: ${mit_model_version:-N/A}
         
         ======== Workflow Output Information =========
         - Embedding Verification: Passed"
@@ -96,16 +122,29 @@ jobs:
         echo "${workflow_info@E}" >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT
         echo "${workflow_info@E}"
+    - name: Check MIT license material
+      id: check_mit_license_material
+      run: |
+        if [[ "${{ github.event.inputs.model_license }}" == "MIT" ]]
+        then
+          echo "Uploading MIT licensed model"
+          if [[ "${{ github.event.inputs.mit_copyright_statement }}" == "" && "${{ github.event.inputs.mit_attribution_website }}" == "" && "${{ github.event.inputs.mit_model_version }}" == "" ]]
+          then
+              echo "missing materials for MIT model"
+              exit 1
+        fi
     - name: Initiate license_line
       id: init_license_line
       run: |
-        echo "verified=:white_check_mark: — It is verified that this model is licensed under Apache 2.0" >> $GITHUB_OUTPUT
-        echo "unverified=- [ ]  :warning: The license cannot be verified. Please confirm by yourself that the model is licensed under Apache 2.0  :warning:" >> $GITHUB_OUTPUT
+        echo "verified_apache=:white_check_mark: — It is verified that this model is licensed under Apache 2.0" >> $GITHUB_OUTPUT
+        echo "verified_mit=:white_check_mark: — It is verified that this model is licensed under MIT, and we have enough materials to generate the attribution file" >> $GITHUB_OUTPUT
+        echo "unverified=- [ ]  :warning: The license cannot be verified. Please confirm by yourself that the model is licensed under Apache 2.0 or MIT with enough materials  :warning:" >> $GITHUB_OUTPUT
     outputs:
       model_folder: ${{ steps.init_folders.outputs.model_folder }}
       sentence_transformer_folder: ${{ steps.init_folders.outputs.sentence_transformer_folder }}
       workflow_info: ${{ steps.init_workflow_info.outputs.workflow_info }}
-      verified_license_line: ${{ steps.init_license_line.outputs.verified }}
+      verified_apache_license_line: ${{ steps.init_license_line.outputs.verified_apache }}
+      verified_mit_license_line: ${{ steps.init_license_line.outputs.verified_mit }}
       unverified_license_line: ${{ steps.init_license_line.outputs.unverified }}
 
   # Step 3: Check if the model already exists in the model hub
@@ -175,11 +214,15 @@ jobs:
       - name: Export Arguments
         run: | 
           echo "MODEL_ID=${{ github.event.inputs.model_id }}" >> $GITHUB_ENV
+          echo "MODEL_LICENSE=${{ github.event.inputs.model_license }}" >> $GITHUB_ENV
           echo "MODEL_VERSION=${{ github.event.inputs.model_version }}" >> $GITHUB_ENV
           echo "TRACING_FORMAT=${{ github.event.inputs.tracing_format }}" >> $GITHUB_ENV
           echo "EMBEDDING_DIMENSION=${{ github.event.inputs.embedding_dimension }}" >> $GITHUB_ENV
           echo "POOLING_MODE=${{ github.event.inputs.pooling_mode }}" >> $GITHUB_ENV     
-          echo "MODEL_DESCRIPTION=${{ github.event.inputs.model_description }}" >> $GITHUB_ENV     
+          echo "MODEL_DESCRIPTION=${{ github.event.inputs.model_description }}" >> $GITHUB_ENV
+          echo "MIT_COPYRIGHT_STATEMENT=${{ github.event.inputs.mit_copyright_statement }}" >> $GITHUB_ENV
+          echo "MIT_ATTRIBUTION_WEBSITE=${{ github.event.inputs.mit_attribution_website }}" >> $GITHUB_ENV
+          echo "MIT_MODEL_VERSION=${{ github.event.inputs.mit_model_version }}" >> $GITHUB_ENV
       - name: Autotracing ${{ matrix.cluster }} secured=${{ matrix.secured }} version=${{matrix.entry.opensearch_version}}
         run: "./.ci/run-tests ${{ matrix.cluster }} ${{ matrix.secured }} ${{ matrix.entry.opensearch_version }} trace"
       - name: Limit Model Size to 2GB
