Actual -> Demo
Signed-off-by: Thanawan Atchariyachanvanit <latchari@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -48,11 +48,12 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref == 'refs/heads/main'
-      run: |
-         echo "This workflow should only be triggered on 'main' branch"
-         exit 1
+# DEMO
+#     - name: Fail if branch is not main
+#       if: github.ref == 'refs/heads/main'
+#       run: |
+#          echo "This workflow should only be triggered on 'main' branch"
+#          exit 1
     - name: Initiate folders
       id: init_folders
       run: |
@@ -117,8 +118,8 @@ jobs:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
-          role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
+          aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
+          role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
           role-session-name: checking-out-model-hub
       - name: Check if TORCH_SCRIPT Model Exists
         if: github.event.inputs.tracing_format == 'TORCH_SCRIPT' || github.event.inputs.tracing_format == 'BOTH'
@@ -126,7 +127,7 @@ jobs:
           TORCH_FILE_PATH=$(python utils/model_uploader/save_model_file_path_to_env.py \
               ${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} ${{ github.event.inputs.model_id }} \
               ${{ github.event.inputs.model_version }} TORCH_SCRIPT)
-          aws s3api head-object --bucket ${{ secrets.MODEL_BUCKET }} --key $TORCH_FILE_PATH > /dev/null 2>&1 || TORCH_MODEL_NOT_EXIST=true
+          aws s3api head-object --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --key $TORCH_FILE_PATH > /dev/null 2>&1 || TORCH_MODEL_NOT_EXIST=true
           if [[ -z $TORCH_MODEL_NOT_EXIST ]]
           then
             echo "${{ github.event.inputs.model_id }} already exists on model hub for TORCH_SCRIPT format and ${{ github.event.inputs.model_version }} version."
@@ -138,7 +139,7 @@ jobs:
           ONNX_FILE_PATH=$(python utils/model_uploader/save_model_file_path_to_env.py \
             ${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} ${{ github.event.inputs.model_id }} \
             ${{ github.event.inputs.model_version }} ONNX)
-          aws s3api head-object --bucket ${{ secrets.MODEL_BUCKET }} --key $ONNX_FILE_PATH > /dev/null 2>&1 || ONNX_MODEL_NOT_EXIST=true
+          aws s3api head-object --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --key $ONNX_FILE_PATH > /dev/null 2>&1 || ONNX_MODEL_NOT_EXIST=true
           if [[ -z $ONNX_MODEL_NOT_EXIST ]]
           then
             echo "${{ github.event.inputs.model_id }} already exists on model hub for ONNX format and ${{ github.event.inputs.model_version }} version."
@@ -201,14 +202,14 @@ jobs:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
-          role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
+          aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
+          role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
           role-session-name: model-auto-tracing
       - name: Dryrun model uploading
         id: dryrun_model_uploading
         run: |
-          dryrun_output=$(aws s3 sync ./upload/ s3://${{ secrets.MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} --dryrun \
-            | sed 's|s3://${{ secrets.MODEL_BUCKET }}/|s3://(MODEL_BUCKET)/|' 
+          dryrun_output=$(aws s3 sync ./upload/ s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }} --dryrun \
+            | sed 's|s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/|s3://(MODEL_BUCKET)/|' 
           )
           echo "dryrun_output<<EOF" >> $GITHUB_OUTPUT
           echo "${dryrun_output@E}" >> $GITHUB_OUTPUT
@@ -276,13 +277,13 @@ jobs:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
-          role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
+          aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
+          role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
           role-session-name: model-uploading
       - name: Copy Files to the Bucket
         id: copying_to_bucket
         run: |
-          aws s3 sync ./upload/ s3://${{ secrets.MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }}
+          aws s3 sync ./upload/ s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/${{ needs.init-workflow-var.outputs.sentence_transformer_folder }}
           echo "upload_time=$(TZ='America/Los_Angeles' date "+%Y-%m-%d %T")" >> $GITHUB_OUTPUT
     outputs:
       upload_time: ${{ steps.copying_to_bucket.outputs.upload_time }}
@@ -404,9 +405,10 @@ jobs:
         uses: actions/checkout@v3
       - name: Trigger Jenkins Workflow with Generic Webhook
         run: |
+          jenkins_url=${{ secrets.JENKINS_URL }} # DEMO
           jenkins_trigger_token=${{ secrets.JENKINS_ML_MODELS_RELEASE_GENERIC_WEBHOOK_TOKEN }}
           base_download_path=${{ needs.init-workflow-var.outputs.model_folder }}
           version=${{ github.event.inputs.model_version }}
           format=${{ github.event.inputs.tracing_format }}
           jenkins_params="{\"BASE_DOWNLOAD_PATH\":\"$base_download_path\", \"VERSION\":\"$version\", \"FORMAT\":\"$format\"}"
-          sh utils/model_uploader/trigger_ml_models_release.sh $jenkins_trigger_token "$jenkins_params"
+          sh utils/model_uploader/trigger_ml_models_release.sh $jenkins_trigger_token "$jenkins_params" $jenkins_url
diff --git a/.github/workflows/update_model_listing.yml b/.github/workflows/update_model_listing.yml
--- a/.github/workflows/update_model_listing.yml
+++ b/.github/workflows/update_model_listing.yml
@@ -14,36 +14,37 @@ jobs:
       bucket_model_listing_file_path: ml-models/model_listing/pre_trained_models.json
       repo_model_listing_path: ./utils/model_uploader/model_listing/pretrained_model_listing.json
     steps:
-    - name: Fail if branch is not main
-      if: github.ref == 'refs/heads/main'
-      run: |
-         echo "This workflow should only be triggered on 'main' branch"
-         exit 1
+# DEMO
+#     - name: Fail if branch is not main
+#       if: github.ref == 'refs/heads/main'
+#       run: |
+#          echo "This workflow should only be triggered on 'main' branch"
+#          exit 1
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
-        aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
-        role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
+        aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
+        role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
         role-session-name: update-model-listing
     - name: List Models
       run: |
-        aws s3api list-objects --bucket ${{ secrets.MODEL_BUCKET }} --prefix "ml-models/huggingface/" --query "Contents[].{Key: Key}" --output text | grep "/config.json$" >> config_paths.txt
+        aws s3api list-objects --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --prefix "ml-models/huggingface/" --query "Contents[].{Key: Key}" --output text | grep "/config.json$" >> config_paths.txt
         echo $(cat current_models.txt)
     - name: Download config files
       run: |
         mkdir config_folder
-        aws s3 cp s3://${{ secrets.MODEL_BUCKET }}/ml-models/huggingface/ config_folder --recursive --exclude "*" --include "*/config.json"
+        aws s3 cp s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/ml-models/huggingface/ config_folder --recursive --exclude "*" --include "*/config.json"
         echo $(ls config_folder)
     - name: Get Current Model Listing for Reference
       run: |
-        aws s3api head-object --bucket ${{ secrets.MODEL_BUCKET }} --key ${{ env.bucket_model_listing_file_path }} > /dev/null 2>&1 || NOT_EXIST=true
+        aws s3api head-object --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --key ${{ env.bucket_model_listing_file_path }} > /dev/null 2>&1 || NOT_EXIST=true
         if [[ $NOT_EXIST ]]
         then
           echo "[]" >> old_pre_trained_models.json
         else
-          aws s3 cp s3://${{ secrets.MODEL_BUCKET }}/${{ env.bucket_model_listing_file_path }} old_pre_trained_models.json
+          aws s3 cp s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/${{ env.bucket_model_listing_file_path }} old_pre_trained_models.json
         fi
     - name: Set Up Python
       uses: actions/setup-python@v2
